### ISSUE TITLE
Change Video Icon

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#1191]
### User Story

As a user browsing the home feed, I want to know that a piece of content has a video, but not think I can click the icon to play the video.

### Description

A bit of feedback we are getting is that the "Play" button on a content card is confusing because users think they can click it to start the video. Maybe it should be a camera icon or something seemingly less clickable???

![original](https://user-images.githubusercontent.com/2659478/68158824-734c6900-ff1e-11e9-9798-ff512b9270af.jpg)

### Acceptance Criteria

* [ ] It should [SPEC_DETAIL]

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by redreceipt** [comment]
@kevin-birdy what do you think about this?

**Comment by kevin-birdy** [comment]
Ya, we've had a good bit of discussion about this :)

When they click the play icon, is the expectation that the video would automatically start as a thumbnail without them going to the weekend experience page? If you could elaborate a bit on the feedback and what exactly users were expecting that would be great. Because from the initial smoke tests it seemed as though even if they thought that was an individual tappable area, it was still accomplishing the goal of taking them to the weekend experience which mitigated confusion because they were presented with the thumbnail alongside everything else.

**Comment by redreceipt** [comment]
They simply thought a video would start playing somewhere

--
Michael Neeley
Junior Web Developer
NewSpring Church
www.newspring.cc
Cell: (803) 622-6599

**Comment by kevin-birdy** [comment]
Ya, I guess what I was specifically interested in was if they thought a video would start playing on the current page, or if they'd be taken to a new page where the video would be playing.

i.e. is it a _separate_ CTA? or is there only _one_ CTA on the card and that is to tap the icon to immediately play a video. No worries if the distinguishment wasn't made I was just trying to gather info :)

The full white play button was supposed to 1) draw attention to the featured card 2) increased likelihood of the card being tapped 3) indicate a video is present

So that makes me wonder...have you experienced the same feedback on `HighlightCard` where the play icon is more transparent?

<img width="358" alt="Screen Shot 2019-11-04 at 3 51 12 PM" src="https://user-images.githubusercontent.com/41083408/68164759-f4a1fc80-ff1a-11e9-9df2-2ea368e3bb57.png">

**Comment by redreceipt** [comment]
I'm not sure what CTA means. They didn't specify where they thought it
should it play, just that it was confusing that it didn't play.

My thoughts on 1, 2, and 3 you have listed, we don't really have to draw
extra attention to it, it's the only thing they see when you first open the
app. And maybe a different less confusing icon could still communicate
there's a video attached to it?

--
Michael Neeley
Junior Web Developer
NewSpring Church
www.newspring.cc
Cell: (803) 622-6599

**Comment by kevin-birdy** [comment]
Sorry...CTA is "call to action." I need to not rely on acronyms so much 😅

Which is kind of why I was especially interested in whether we've received this feedback on _just_ the white play icon? Or on both the white _and_ the transparent play icon...

Because if it was only for the bright white one, then I would vote we go transparent for everything. That way it still indicates video without calling too much attention and tricking users into thinking it's an entirely separate CTA from the card itself.

**Comment by kevin-birdy** [comment]
If both are confusing, then yes we can explore other icons. At the moment, I don't think anything in Core works all that well. So we probably would have to open up the conversation about adding new icons...

**Comment by kevin-birdy** [comment]
That is a good question. I'm going to add this to our "To Discuss" list and will report back ASAP.

**Comment by richarddubay** [comment]
Just as a point of reference we have/had a video camera icon in the NewSpring app for things like series and sermons and I can't remember anyone ever thinking that they could play the video from there but that it was a piece of content _with_ a video. Maybe that's because at the same time we had a document icon on things like articles, and a headphones icon for music along with one word descriptive text. I'll post some screenshots I found below.

In this case, maybe a video camera icon would serve the purpose of letting a person know that there is a video attached to this piece of content while not having the perceived intent of actually playing a video like the play icon has.

![IMG_7E072EBC3C3E-1](https://user-images.githubusercontent.com/3229463/69495534-03cef700-0e96-11ea-8c4e-e777d0ba0a7c.jpeg)
![IMG_A7383C9BB32C-1](https://user-images.githubusercontent.com/3229463/69495536-04678d80-0e96-11ea-8e41-282ffc9e0089.jpeg)

**Comment by conrad-vanl** [comment]
Hey guys!

Thanks so much for posting this and bringing it up. I do not believe that we have enough information to consider a core change yet. I agree that what is in core may not be optimal, but changing it now in core to something would just as likely perform worse than better as we don't have a way to exactly measure changes in core before they're pushed out to everyone.

Instead, I'd like to help you all understand usage behavior and experiment with changes to see what performs optimally, and report that back so that core can make a better informed decision on what to do.

Right now you are validating this as a problem based on unsolicited qualitative feedback from users. This is great! And your team is going to be the best at interpreting this feedback and deciding if a problem is validated based on the feedback you're receiving. You can use quant data in Amplitude to support your opinion on this, or gain more insight...but ultimately you'll have to trust your teams relationship to the product and your users and make a guess on whether you believe this is a valid problem. Not all feedback you receive will point to valid problems (vocal minority, etc) but I believe you have brought up good points and there might already be enough here to consider this as a potential area for improvement.

So here's what I'd do:

1. Understand what the current conversion baseline is
2. Make sure the team is aligned on this opportunity and what appetite there is for making changes
3. Experiment with changes to your product and understand impact with your conversion rates
4. Share data with core / Apollos so that we can all improve our church apps and learn from each other

----

I created a [conversion funnel in Amplitude](https://analytics.amplitude.com/newspring-apollos/chart/new/h4nkvkx) for the "Hallowed Be Thy Name" sermon 

![image](https://user-images.githubusercontent.com/103927/72907396-68bd9680-3cf9-11ea-90a5-f73c1c0b2c60.png)

It's showing that roughly 40% of users that opened the app on the Sunday that this sermon was "live" actually opened the sermon. It doesn't matter if you consider that conversion rate good or bad, but whether this is your baseline (you probably want to look at multiple Sundays to track true average).

You'll also want to compare with general home feed => content item conversion rates to make sure there's no negative impact to general conversion rates:

![Screen Shot 2020-01-22 at 9 29 43 AM](https://user-images.githubusercontent.com/103927/72907618-bfc36b80-3cf9-11ea-8969-8595888d2a70.png)

----

Changes I would consider experimenting with (spitballing):

1. Passing `hasAction={false}` to the `FeaturedCard` component so it displays no icon
2. Trying different icons passed to `actionIcon`
3. If you're using some specific language, such as "Open your apps to find the weekend experience" then maybe experiment with changing the label on the FeaturedCard instead of the icon - make the label say "Weekend Experience" or "The Weekend" or something like that...keep the language consistent and represented in the UI 

---

@redreceipt hopefully this gives you and your team some next steps and a pathway for helping us making core better! Feel free to close this or continue the discussion.

**Comment by redreceipt** [comment]
Love it! I'll tweak some knobs...
