### ISSUE TITLE
[💄] Take first stab at integrating themes in graphql api

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#143]
#### Problem Details _(Optional)_

* GraphQL api should describe how the app is to be themed, and how individual content items are to be themed.
* Should the graphql api have a tight contract to the app for describing theme - as in - should the graphql expose theme properties like `backgroundColor`, or data-bound properties like `seriesColor`?

#### Acceptance Criteria _(Optional)_

* [ ] Something in app is styled based on properties from graphql api

**Comment by conrad-vanl** [comment]
@burkeshartsis would love your thoughts on this, specifically:

> Should the graphql api have a tight contract to the app for describing theme - as in - should the graphql expose theme properties like backgroundColor, or data-bound properties like seriesColor?

I think there's two ways we could go about this. In our graphql schema, we could define a `theme` type, that matches the shape of theme in the app:

```
type Theme {
   colors: {
     primary,
     secondary,
     // ...etc
   },
   sizing: {
     baseUnit,
     // ... etc
   },
   // ... etc
}
```

and then items returns in the graphql schema can have a `theme` property that returns the "theme" for that item, if there are any overrides. This allows for a ton of flexibility on the content creation side, but creates a pretty tight contract between the api and the frontend.

Or...alternatively, items in the api could just have values set on them that describe specific things, and our frontend knows which values to look at for the specific content, like:

```
Series {
   seriesBrandColor
}
```

```
Devotional {
   devotionalBrandColor
}
```

etc


Personally, I'm leaning towards the first, but I also think there's potentially room to simplify our theme structure some

**Comment by burkeshartsis** [comment]
First, I've worked with a bunch of different theming engines in a bunch of different languages/frameworks and I would not say we have a complex theme. I think we could simplify the default > dark/light relationship a bit by being more explicit in how we define colors in each type (rather than a conical source in default that is referenced). We could probably simplify/be more explicit with button/CTA coloring as they currently live outside of the regular color definitions. All that is to say, I don't believe we have a complex theme structure but I suppose it could be improved 🙃 

To your main question, I like idea 1. The mental model is straight forward and predictable. I can see it creating a lot of options on the Rock side for how this is implemented as well. To the extent that at the content creation level idea 2 could compile within Rock into idea 1 before it's exposed within the theme object. I, however, do not think that is necessary at this juncture. I can see idea 1, however, creating a lot of issues. Even if we keep a strict schema, do we support additional styles/theme overrides (styles not defined in the original schema)? Part of me thinks, at least in the beginning probably not. Looking at all the attention the WP community has put into it's theming controls regardless of whether Rock goes that direction this at least makes it possible.

**Comment by conrad-vanl** [comment]
Alright @burkeshartsis I put some thought to this, and I have some suggestions.

First...instead of trying to expose the entirety of our theme definition in our graphql, I think we can support a small sub-set instead. This will help limit the amount of bugs cropping up, like guarding against style changes that could break the app such as specifying a font-family that's not installed.

For now, I'm calling this a `Palette`, and it looks something like this:

```graphql
type Palette {
  type # "light" or "dark"
  primary # the primary / brand color
  accent # a secondary color that compliments the primary
  background # background color for screens, such as lists.
  paper # background color for elements containing content, such as cards 
  text # text color for content
  inactive # color for inactive elements (such as unselected checkbox or the bottom underline on text inputs)
  disabled # color for disabled elements
  placeholder # color for placeholder text
  alert # color for alerts or errors shown to the user
}
```

I think naming and such above can be massaged a bit, but in general this should provide all of the colors we'd need to infer all of our app's colors.

This does remove the primary/secondary/tertiary, lightPrimary, lightSecondary, etc naming scheme. Which I think is both too many colors to keep up with and hard to remember what is used for what.

I think this will still build back into a larger theme definition that looks very similar to what we currently have, that looks like:

```
{
  colors: { ... },
  typography: { ... },
  breakpoints: { ... },
  sizing: { ... },
  alpha: { ... },
  type: { ... },
  types: { light: { ... }, dark: { ... } },
  shadows: { ... },
  buttons: { ... },
  helpers: { ... },
  overrides: { ... },
}
```

We might just end up massaging the names a bit, and dropping the use of `secondary` and `tertiary` and replacing with names that are more specific/explicit (such as `accent`, `disabled`, etc)

**Comment by burkeshartsis** [comment]
Some comments from our conversation around exploring your Palette idea.

First, I struggle with the idea of exposing an additional element as part of the theme API that is not directly part of the part of the theme itself. It just feels like we have a portable structure already why abstract it further. I purpose we expose a subset of our theme `type` api. Types currently allow you to override any portion of a theme. For now, I think the safest route is to expose colors and simply compile the theme object down from gql > current type > default theme.

With regards to the palette's simplified color definitions, I agree these could use a refactor especially in the way of removing colors we don't need/use. I think a lot of our color bloat is due to the fact that we support a dark and light interface. Regardless, a different brand can always extend this to have more or less for their needs. There isn't really a wrong way to name things here but my recommendation is to keep color definitions abstract and decoupled from how they are used. In my experience, designers use a locked set of colors in a variety of ways. If we define a shade of brownish-gray as `placeholder` now, but need to use it for a loading spinner later we either use a named color out of context or are forced to duplicate colors with new names. There are, of course, exceptions to this statement. Text and background colors need to be consistent and for us they need to be reversible for dark/light theming as well. `warning`, `caution`, `alert`, and `success` can sometimes have color definitions outside of brand coloring that should also stay consistent but it's a slippery slope that I recognize is hard to define when/where exactly you stop.

**Comment by burkeshartsis** [comment]
Additionally, I think we can refactor our button coloring to be much much simpler as well.

**Comment by burkeshartsis** [comment]
from: @conrad-vanl via slack:
> I flushed out the "on" idea a little bit. I'm actually kind of digging this....thoughts?
> 
> What I'm trying to potentially showcase here - is we have a very small set of "base" colors, then a set of "shades" that are used `on` top of each of the base colors. So we get nice abstract names, but structure at the same time
> ```
> colors: {
>  primary: '#00676D',
>  secondary: '#33ee99',
>  screen: '#f1f1f1',
>  paper: '#ffffff',
>  danger: '#dc3545',
> ​
>  on: {
>   primary: {
>    shade1: 'white',
>    shade2: 'mix(white, colors.primary, 25%)',
>    shade3: 'mix(white, colors.primary, 50%)',
>    shade4: 'mix(white, colors.primary, 75%)',
>   },
>   secondary: {
>    shade1: 'white',
>    shade2: 'mix(white, colors.secondary, 25%)',
>    shade3: 'mix(white, colors.secondary, 50%)',
>    shade4: 'mix(white, colors.secondary, 75%)',
>   },
>   screen: {
>    shade1: '#303030',
>    shade2: '#505050',
>    shade3: '#a5a5a5',
>    shade4: '#dbdbd9',
>   },
>   // ... and so on
>  },
> }
> ```
> so for example, headers might be `shade1`, icons and text could be `shade2`, accent items (like inactive form elements) `shade3`, disabled state is `shade4`, etc

**Comment by burkeshartsis** [comment]
Ok! So I like where you have taken the on" idea here. I like that the relationships it creates between colors are both meaningful to the developer and in some ways flexible to the designer. Each `on` object is almost like a two-color palette that you can trust works together. I see a couple situations here worth exploring which I believe may be addressable with some work on naming.

1. With the current naming, `shade#` you are locked into each numbered variant being a shade of the same color (as shown in your example above). In color theory, however, it is common to place contrasting or complementary colors on top of each other. The primary McDonald's color palette is yellow on red but sometimes white on red if legibility is an issue. In some cases its both yellow and white on red in the case of the corporate logo. In a situation like this HMW allow contrasting, complementary, or other colors that work "on"/within a given color palette.

    -  One possible solution that doesn't seem to conflict with this direction,

        ```
        colors: {
          primary: '#00676D',
          ​// ..
        
        on: {
          primary: {
            default: 'white',
            tint1: 'mix(white, colors.primary, 25%)',
            complement: '#FF6600',
        },
        // ... and so on
        ```
2. Another thing I am worried this will lead to is the duplication of color values under new names. In your example, above `colors.paper`, `colors.on.primary.shade1`, and `colors.on.secondary.shade1` are all the same. Now I understand it was just an example but I believe it will be more common place than we think. Especially with analogous color schemes like ours where dark or light text look equally good on primary, secondary, et. al. brand colors. To that end, a color system that was meant to add meaning only adding multiple meanings to the same thing. This point, unfortunately, I do not see a way around.

**Comment by burkeshartsis** [comment]
**Some additional thoughts**

The more I dig into this the more I feel like our current naming is pretty strong and in alignment with vocabulary a designer understands and uses. While I recognize that an engineer is forced to go hunting for the meaning/value of `colors.background.primary` to know if it will return the correct value I am not sure the "on" system will solve this either. The "on" system is highly visual; a color map if you will. I think engineers will still have to reference this "map" in making sure they selected the right color.

I do think we can simplify the number of color references we have. I don't think we need 8 different background colors. These seems like a bit much. It's entirely possible that some of these colors might just be disorganized and not really be background colors at all. `colors.background.inactive` for example could be used for text, buttons, or inputs.
