### ISSUE TITLE
[Scripture] Update Scripture component to new API format

### ISSUE THREAD

**Issue by IsaacHardy** [ApollosProject/apollos-prototype#249]
v3 of the ESV api has a different format for the data coming to client. This issue is for updating said component to display the content.

**Comment by richarddubay** [comment]
@IsaacHardy As you know, we ended up changing the API from ESV to API.Bible. So this task has kind of changed. Also, I ended up just wrapping ALL of those changes into [#216](https://github.com/ApollosProject/apollos-prototype/issues/216) because that PR needed to get merged _before_ we could work on any other scripture stuff. 

So, not sure how you want to handle this issue?
