### ISSUE TITLE
Look into API.Bible Copyright Needs

### ISSUE THREAD

**Issue by richarddubay** [ApollosProject/apollos-prototype#309]
## User Story

As a developer, I want to display scripture accurately (including any necessary copyright information) so that I can spread the Good News of Jesus Christ _and_ not get sued.

#### Acceptance Criteria _(Optional)_

* [ ] Determine whether or not copyright information is required to be displayed on the scripture that we are pulling from API.Bible.
* [ ] If so, add the copyright information to the `<Scripture>` component. This will require pulling the copyright information in our API and then displaying that information in the app.

**Comment by richarddubay** [comment]
@conrad-vanl Does this cover everything?

**Comment by redreceipt** [comment]
@richarddubay are we currently using the Fair Use Management System (FUMS) when we display scripture anywhere?

**Comment by redreceipt** [comment]
also, FYI, there's a limit of 500 queries a day, if we want more we have to ask for it.

**Comment by redreceipt** [comment]
http://el.bibles.org/pages/legal/#terms-api
http://el.bibles.org/pages/api/documentation/fums
http://el.bibles.org/versions

**Comment by redreceipt** [comment]
A. Will:

- Comply with the Terms and Conditions of Use of the ABS Bible Search web site.
- Fully honor the copyrights of all Texts and display the appropriate copyright notices and trademarks as set forth in the Versions Index. Copyright notices and information are included in every API response.
- Implement the Fair Use & Copyright Management System as documented here prior to using the API. The purpose of the Fair Use & Copyright Management System is explained in the introduction to the API
- Periodically clear cache (at least every 14 days) to ensure that you are working with the latest version of the Texts, and that any bug-fixes we've applied to the service are included in the content you receive.

B. Will Not:

- Make any modification to the Texts.
- Charge a fee for access to or use of the Texts.
- Impugn the reputation of any Text or the copyright owner of any Text.
- Use any Text in any material or communication that (a) advocates or encourages violence: (b) may reasonably be perceived as unlawful, defamatory, offensive, obscene, vulgar, pornographic, threatening, abusive, misleading, deceptive, or bigoted (racially, ethnically, or otherwise objectionable); (c) contains false or unauthentic text; or (d) contains inappropriately negative comments about the Bible or Jesus Christ, or any other religious sect, text or organization.
- Perform more than 5,000 queries a day without advance written permission from ABS, which may be requested by contacting support@bibles.org.
- Sell, share, or publish your access key.
