### ISSUE TITLE
[Push Notifications] Create Rock Transport for OneSignal

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-prototype#471]
We can use https://github.com/NewSpring/Rock/blob/master/Rock/Communication/Transport/Firebase.cs as an example of a transport. To send to specific users, you will want to use the "include_external_user_ids" field.

https://documentation.onesignal.com/reference#section-send-to-specific-devices

Contact @vinnyjth for details on the API keys or access to the OneSignal account if you don't have them.

**Comment by richarddubay** [comment]
@cdanwards @redreceipt @IsaacHardy 

For when we get back after the break:

We need to create a new Rock transport that uses One Signal. To make this super simple to get started, let's build it in the same folder as the Firebase one (https://github.com/NewSpring/Rock/blob/master/Rock/Communication/Transport/Firebase.cs) and use the Firebase one as an example. We may need to figure out how to make this live someplace else later, but I want to make sure we get started building it first and worry about moving it later. We're also waiting to hear back from Spark about their desire to have this as a core block.

So essentially we just want to write that transport to make the same basic calls as the Firebase one but calling to One Signal instead of Firebase. It _should_ be fairly straight forward. There is a link above (in Vincent's comment) to One Signal's docs. 

One thing Rock does that we will need to figure out how to take into consideration is Rock's ability to determine whether or not a person can be sent a certain type of communication. For example, if we are sending emails to a list and someone on that list doesn't have an email then they get marked with a red X and no email is sent to that person. We will need this same kind of functionality in Rock for these push notifications. Rock has made so many changes since we did this the first time that I'm not exactly sure if that lives in the transport (what we're writing) or the Push Notification medium or someplace else. We'll need to investigate. I want to say that the way we determined this in the past was with a Push Notification attribute on the person, but maybe we can determine that with a call to One Signal to see if their device has a record? I don't think we can necessarily use the person attribute because we shouldn't be forcing a church to have to put an attribute on a person in order to use this feature. Going out to One Signal to see if the device exists seems like a more flexible option if we can pull it off. Again, I'm not exactly sure how to pull this off or even if we have to ... it might be built into Rock now. We'll just need to figure that out.

**Comment by conrad-vanl** [comment]
@richarddubay  how is this going? (I'm gearing up for sprint planning today and auditing our remaining issues)

**Comment by richarddubay** [comment]
@conrad-vanl So the transport and the NuGet package are both done. When Paul (our IT guy) put them on the `apollosrock` instance, something happened and it broke. Getting a 503, Service Unavailable error. Paul created a core-rock instance on my development machine and when I put the DLL's where they needed to go, it worked just fine. Paul then created a core-rock instance that mimicked what `apollosrock` looks like and the DLL's broke that. I'm not a lot of help with this because I don't have access to either of the instances that Paul is working on that are breaking. So really this is just me waiting on him to figure out what's causing the problems. Maybe it's an Azure problem? Maybe it's a problem with not having the right set of other DLL's on a core-rock instance as opposed to what comes from Github? He's not sure yet. We were supposed to get together this morning to see if I could help, but life made that impossible. Does that make sense?

**Comment by richarddubay** [comment]
@conrad-vanl and @vinnyjth How do you guys feel about this one? I feel like everything is probably done now?

**Comment by richarddubay** [comment]
@vinnyjth and @conrad-vanl I'm going to move this issue to "In Review" so that you guys can take a look at it. Vincent, if you have your Rock PersonAlias Id set up in OneSignal, we can send a notification your way to see if you get it. Let me know if you don't know how to do that and I can walk you through it.
