### ISSUE TITLE
Upgrade React-Native to latest

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#503]
We should upgrade to the latest version of React-Native
https://facebook.github.io/react-native/docs/upgrading#projects-built-with-native-code

With this, we can also check for upgrades on core dependencies, like Jest, eslint, etc. Look in both root-level `package.json` and in `apollos-ui-kit/package.json` and `apolloschurchapp/package.json`

**Comment by redreceipt** [comment]
I'll start this one. Quick question for clarity, when running `yarn outdated` what "Workspace" corresponds to which package? It's obvious enough for most of them but I'm just trying to understand how `yarn` works with our package structure.

![screen shot 2019-02-05 at 3 15 19 pm](https://user-images.githubusercontent.com/2659478/52301641-e2c60580-2958-11e9-9e88-b0a3912be9a4.png)

**Comment by redreceipt** [comment]
SHA: a4986f2b

**Comment by redreceipt** [comment]
#523

**Comment by redreceipt** [comment]
`lerna` makes it tricky :)
https://github.com/facebook/react-native/issues/16666

@conrad-vanl quick question: Since I'll have to upgrade each package individually, and then I won't be able to use the utility at the root, what's the purpose of the root `package.json`? Could I simplify by deleting anything in that file?

**Comment by redreceipt** [comment]
Working branch: fb4eaf12
