### ISSUE TITLE
Figure out less, but better path for adding images to Apollos Rock demo content

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#564]
- [ ] TODO: Reach out to IT to see if possible to cherrypick asset attribute item (?) on to Apollos Rock

**Comment by richarddubay** [comment]
So @cdanwards and I did a little research. There are going to be a lot of changes that would have to be made if we were going to get the Asset Manager structure working in Rock. I'm pretty sure we technically couldn't just cherry-pick them either because `apollosrock` isn't a repo that we can just put commits in. It's just the `RockWeb` folder on a server. We'd have to figure out which files to pull at which juncture in time and drop them in the folder (or the DLL's that these changes live in) as well as pull and make migration changes to our database structure. Also, even if we could do this, that kind of defeats the purpose of keeping `apollosrock` as close to a core release as we can to make sure that what we're doing will work for everyone. 

I feel like the best bet isn't to try to pull these changes into our version or Rock right now. We should continue to search for a good way to get images into these content items though. 

@cdanwards @conrad-vanl Thoughts?

**Comment by richarddubay** [comment]
@conrad-vanl I just went ahead and spent some time today getting all the images for all the content uploaded by hand. It would have taken a lot longer to figure out how to get some script to do some other thing to make it happen. This solves the problem of needing images on all the things.
