### ISSUE TITLE
Need catch for incorrectly formatted content

### ISSUE THREAD

**Issue by cdanwards** [ApollosProject/apollos-prototype#996]
### Details

If a Rock user doesn't correctly input content into the CMS system, sometimes it can have unintended consequences in the app.

![Screen Shot 2019-08-13 at 4 22 39 PM](https://user-images.githubusercontent.com/8878532/63026497-4d607c80-be79-11e9-995d-71e2d74aadd8.png)

### Expected Behavior

Content should display as intended, with some catches when the input is slightly off.

### Actual Behavior

Content isn't formatted as intended if tags are left off in the content input on Rock. 
Screenshot above is missing a `<p>` wrapper.

### Possible Fix

Check to see if text is outside the bounds of wrapping tags and add one if so.

**Comment by cdanwards** [comment]
@conrad-vanl Is this something that we should care about or manage? Or should this be on the content teams at each church to make sure they're inputting correctly?

I've put a little bit of work into coming up with solutions but React doesn't like to manipulate nodes...

**Comment by conrad-vanl** [comment]
The best way we can try to handle this is by enforcing valid html at the graphql side. We have some tools to help with this. It’s unfortunate that the rock wysiwyg allows for invalid html. 

But yeah, it’s likely impossible for our html renderers to eloquently handle invalid html, and no matter what, in the case of invalid html we will likely not be able to render what the content author intended.

**Comment by richarddubay** [comment]
@conrad-vanl The thing here is that this isn't even invalid HTML. It's just a link that doesn't live inside a `<p>` tag. Checking for invalid HTML is great, and we should do it. But what about when the HTML is valid and we just don't handle it well?

**Comment by richarddubay** [comment]
It seems like what we're saying is that it isn't that the HTML is invalid, per sé ... it's that the HTML is invalid to _our rules_. Our parser just doesn't handle it. I think that's an important distinction.

**Comment by cdanwards** [comment]
@conrad-vanl So I spent some time looking into `sanitize-html` and `natural` libraries that we're using on the graphql side to help with the html content. I wasn't able to find any use cases there where it can reject invalid html or search for characters outside of tags. Are these the only tools that you were referring to, or am I missing another tool?

**Comment by conrad-vanl** [comment]
Ahhh gotcha @richarddubay. Could you paste the html example in here so I can look at it?

**Comment by cdanwards** [comment]
`<h4>1. Be slow </h4>
<p>What would it look like to live your life at half-speed? When you’re flying down the highway, you take in much less of what you see than if you’re walking beside the road. When you do your regular everyday things, go slow enough to be aware of yourself doing them.</p>
Take time to notice the flowers blooming, to wave to the sweet elderly couple walking by the house, or to stop for a real conversation with the new girl at school. When we rush through our days, bouncing from one place to the next, 
<a href="https://newspring.cc/articles/slow-down-without-feeling-guilty-about-it">we miss so much</a>. 
Put the phone down and look around instead of mindlessly scrolling or cramming busy into every moment.
<p></p>
<p>
<img src="https://lh6.googleusercontent.com/P1WgtTBq61cgV51_UVejnMeMbr0Cs6KH0QXjcMeYKs6ceZHWFUURYcMhVALHqaqIOUqLITIF2IoTvCUVVv-aRiHeqVjb7gBlPnI991XHl4bjDqkxC-ww_Nd-MVJFW4D87cs9QEbx" />
<br />
</p>`

**Comment by conrad-vanl** [comment]
Hmmm. Interesting. I’m tempted to say this is a bug. I bet if you wrapped that block I’d text that contains the link in a P tag it would work fine?

**Comment by richarddubay** [comment]
@conrad-vanl Yep. Inside the `<p>` tags things work fine. Outside of them, not so much.

**Comment by conrad-vanl** [comment]
What happens if we wrap the entire html content inside of a `<p>` tag? we could do that on the graphql side. 

We'd effectively end up with an `<H1>` tag inside of `<p>` or double nested `<p>` tags but I think our renderer would handle that fine.

Other option is to play with this function - https://github.com/ApollosProject/apollos-prototype/blob/master/packages/apollos-ui-htmlview/src/HTMLView/defaultRenderer.js#L29 and this line - https://github.com/ApollosProject/apollos-prototype/blob/master/packages/apollos-ui-htmlview/src/HTMLView/defaultRenderer.js#L59-L66

**Comment by cdanwards** [comment]
@conrad-vanl This has been an interesting issue and I tried a few thoughts that I had:
On the front end I tried
1) Isolating text nodes whose parent node was a link and adding a paragraph component, but kept running into the React error of Views not being supported within Text.
2) Wrapping the links in  Paragraph component to apply inline styles, but this also doesn't fix the disjointed paragraph.
3) I tried appending the link nodes that are orphaned to the previous parent paragraph node as children but couldn't get the Node object methods to work in React.

I also looked into wrapping the whole htmlContent in a p tag on the back end but couldn't figure out how to do that without writing a custom method for the html sanitizer or something like that. Is there a way for the backend to recognize text outside of a tag and throw a bugsnag error or reject the content somehow?

Because right now the only use case that we can think of is that a link node that is outside of a p tag but surrounded by text nodes that don't have parents, I'm checking for that so that we can inform the content team. 

Do you have any other ideas or something I'm missing?

**Comment by conrad-vanl** [comment]
You're right that this is a complex issue. 

To wrap the html content in a `<p>` tag, you could do that on the graphql side by changing [this line](https://github.com/ApollosProject/apollos-prototype/blob/master/packages/apollos-data-connector-rock/src/content-items/resolver.js#L15) to something like:

```javascript
   htmlContent: ({ content }) => sanitizeHtml(`<p>${content}</p>`),
```

**Comment by burkeshartsis** [comment]
Some observation from #1085. Seems like we are dealing with the same core problem.

Ok so this happens a lot with WYSIWYG editors. It can happen for a variety of reasons but it's usually the result of people writing content in one place and copy/pasting it into a CMS's WYSIWYG editor. Some editors try to get around this by providing "paste as/from" buttons which Rock has but these rarely work well namely because there are just so many possible source editors. I digress. 

The issue in #1085 and here is compounded because we are then parsing it yet again for display in the app. For #1085 our parser is rendering the following code funny.

<img src="https://user-images.githubusercontent.com/2053547/66339972-3dfa2e80-e912-11e9-9dba-c79dda8fa7b7.png" width='50%' />

```[...] you’ll gain a deeper understanding of who God is, what He wants for you, and what it means to be part of His family.<br></div><div><br></div><ul><li>Sunday, Oct. 6 - Connect to Salvation</li>[...]```

This is a case of jank/excessive HTML markup, that to be honest, I am surprised your website renders as cleanly as it does. I checked and it's rendering the same HTML it just doesn't look broken. When our parser sees this it renders a closing paragraph around the text that ends at `His family.` then a line break for every `<br>` and a new paragraph for the next `<ul>`. So you end up with padding at the end of a paragraph (good 👍) and then 2 additional line breaks before the `<ul>` (bad 👎) which ends up looking like 3x the space you actually need/want.

**Comment by burkeshartsis** [comment]
So one option I'm seeing is we could add a filter to help catch various `<br> situations and only allow them when they are not the only child or at the end of an element. 

https://github.com/apostrophecms/sanitize-html#filters

**Comment by burkeshartsis** [comment]
In the #1085 case were the links are isolating from their text it's because it is rendering the section below as 5 different paragraphs because they are five separate text nodes in the the html.

<img src="https://user-images.githubusercontent.com/2053547/66345085-4e63d680-e91d-11e9-8586-d7133baa8dbb.png" width="50%" />

**Comment by conrad-vanl** [comment]
@burkeshartsis did you have a branch with some stories showing these failing cases y ou could push up? I'll jump into it and take a look if so

**Comment by burkeshartsis** [comment]
@conrad-vanl ☝️😘
